// <auto-generated />
namespace Votex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GeneralUpdate4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeneralUpdate4));
        
        string IMigrationMetadata.Id
        {
            get { return "201612270359227_GeneralUpdate4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
